### ISSUE TITLE
broken by prop "null" string

### ISSUE THREAD

**Issue by morlay** [dosentmatter/babel-plugin-const-enum#11]
```ts
export const enum SimpleTypes {
  array = "array",
  "boolean" = "boolean",
  integer = "integer",
  "null" = "null",
  number = "number",
  object = "object",
  string = "string",
}
```

will throw error `Property name expected type of string but got null`

**Comment by dosentmatter** [comment]
Hey @morlay, sorry for the delay. Thanks for filing this issue and submitting PR #12.

You are correct that there is a bug with string literal property names. I did some refactoring of the code so I merged #14 instead of #12. I also added tests and added a little more error checking to make sure the property is only either an identifier or string literal before accessing the value. Here is the [exact commit](https://github.com/dosentmatter/babel-plugin-const-enum/pull/14/commits/a05a3a1039f7c4a5f9fa38d05f1a8c41618c4b23). Thanks for your contribution though.

I have published to npm as version 0.0.5 - [github](https://github.com/dosentmatter/babel-plugin-const-enum/tree/0.0.5), [npm](https://www.npmjs.com/package/babel-plugin-const-enum/v/0.0.5)
