### ISSUE TITLE
Allow "constObject" transform to be used on non-constant enums

### ISSUE THREAD

**Issue by slavafomin** [dosentmatter/babel-plugin-const-enum#31]
Hello!

Thank you for this great plugin!

I found out that `constObject` mode works very well for enums optimization. It allows enums to be tree shaken, which is not possible by default, due to IIFE generated by [`tsc`](https://github.com/microsoft/TypeScript/issues/27604) or `babel-typescript-transform`.

I'm very interested in using this transformation for normal non-constant enums. Do you think it would be possible?

The [other plugin](https://github.com/morlay/babel-plugin-typescript-iife-enum/issues/20) doesn't seems to work.

Thanks!

**Comment by dosentmatter** [comment]
Hello. Thank you for using the plugin!

> It allows enums to be tree shaken

I think what you mean is that the [enums are inlined](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums), not tree shaken. [Tree shaking applies to es6 modules for dead code elimination](https://webpack.js.org/guides/tree-shaking/).

> which is not possible by default, due to IIFE generated by tsc or babel-typescript-transform.

I think you are kinda misunderstanding the goal of this plugin.
`tsc` can inline enums. You have to use `const enum` instead of `enum`. Regular `enum`s aren't inlined because they have special features. You can read about regular `enums` in the [docs](https://www.typescriptlang.org/docs/handbook/enums.html#enums). One example of the special features is the reverse mappings. Look closely at the `tsc` IIFE output and you will see what I mean. `tsc` isn't doing an IIFE for no reason. They could have done it without an IIFE, but the IIFE output is concise. Either way, they have to dynamically modify the resulting object because of reverse mappings.
Another feature is allowing [computed members](https://www.typescriptlang.org/docs/handbook/enums.html#computed-and-constant-members).

The reason for this plugin is because `babel-plugin-transform-typescript` doesn't allow transpilation of `const enum`. I think because unlike `tsc`, babel transpiles files in isolation and not as a project like in `tsc`, so it can't import an exported enum, if the enum gets inlined. My plugin allows `const` enums to work in two ways:

1. Just `removeConst` and treat it as a regular enum. No inlining happens. `babel-plugin-transform-typescript` is happy since no `const enum`.
2. `constObject` and depend on minifiers to inline. `babel-plugin-transform-typescript` is happy since no `const enum`. But `babel-plugin-transform-typescript` isn't doing the job of inlining, whereas for `tsc`, it does the inlining, even across modules.


> I'm very interested in using this transformation for normal non-constant enums. Do you think it would be possible?

Yes, that would be possible, but I won't be implementing that, because that doesn't conform to the TypeScript specification. Regular `enum` should not be inlined. If you. want that functionality, you have 2 choices:

1. Manually add `const` to all your `enum`.
2. Write a babel plugin to convert all your `enum` to `const enum`. You have to be careful though because since `const enum` is constant, its values have to be able to be statically determined ie. at compile time. Read the TS spec and you will see some enums that are valid regular `enum` are not valid `const enum`s.

> The other plugin doesn't seems to work.

I'm not really sure I understand the goal of that plugin. It doesn't make sense to me. The readme says:

> This result is not friendly for uglyify.
> 
> So just wrapper IIFE for enum

If an IIFE is not friendly for a minifier, why would you wrap it in another IIFE? Pretty sure that doesn't help. I also tested in a minifier to check. Maybe @morlay can explain. I do recognize that user. He file an [issue on my repo a while back](https://github.com/dosentmatter/babel-plugin-const-enum/issues/11). That issue was in November and his last commit to `babel-plugin-typescript-iife-enum` was in July, so maybe he's using my package now. There is a difference though. His package deals with regular `enum` while mine deals with `const enum`. I just don't really understand the reason for his package though.

I'm gonna close this issue. You can reopen or comment if you have further questions.
