### ISSUE TITLE
[QUESTION] I made a simple fork

### ISSUE THREAD

**Issue by JakubKoralewski** [dosentmatter/babel-plugin-const-enum#35]
[Here's the fork](https://github.com/supercuts/babel-plugin-const-enum-experimental). I added an `experimental` setting, in which I replace all property accesses with the values of the enums. I think this should work for my simple use-case of uninitialized const enums, but could you tell me @dosentmatter what's wrong with this approach and where it fails exactly, so I could be aware if I were to use my fork in prod. I've read that const enums are impossible because the type information is not available, but I really don't see why types would be necessary to inline the values of the enums, given that Babel itself does not mind producing incorrect code.

EDIT: I also added fake hoisting of fake enum variables as well as scoping the enum names in the state object so not to clash with same names in different scopes.

EDIT2: I'm trying to use this now by adding link to the github repo in `package.json` instead of the semver, but I don't get the `lib` directory unfortunately, dunno how to proceed.

EDIT3: I was able to fix the above by changing the `prepublishOnly` script name into `prepare`.

EDIT5: Although enabling the option now triggers an error regarding a non-null expression:
```
./src/pages/index.tsx 284:48
Module parse failed: Unexpected token (284:48)
File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js
You may need an additional loader to handle the result of these loaders.
|         if (entry.isIntersecting) {
|           setTimeout(function () {
>             return inputRef.current!.focus();
|           }, 100);
|         }
```

I don't know why my option triggers this :confused:

**Comment by JakubKoralewski** [comment]
Ok I realise the problem. Importing is not gonna work.

**Comment by dosentmatter** [comment]
@JakubKoralewski

> I've read that const enums are impossible because the type information is not available, but I really don't see why types would be necessary to inline the values of the enums, given that Babel itself does not mind producing incorrect code.

`const enum` are like type information because `const enum` declarations don't generate any output code. Since their declarations are treated like type information, they are ignored by babel and generate no code. Type exports are also removed based on scope information - if you are curious how that works, read #20.

However, the difference between `const enum` and type information is that `const enum` can affect code output generation in certain cases, while type information never does. `const enum` affects code output when enum access gets inlined in your code. This is the reason why babel can't transpile `const enum` and the reason for the existence of my package. Babel transpiles modules in isolation - see TypeScript `isolatedModules` option - so it is impossible for babel to grab `const enum` members from other modules and inline them in the current module. Babel also has no notion of a project (tsconfig) like TypeScript does, Babel just has file in, file out.

So Babel could implement partial support where `const enum`s get inlined within the same module but not import/exported between modules. Try as you might, you won't be able to get around Babel's design (or restriction) of transpiling modules in isolation.

The way my plugin works around Babel's limitations is to transpile `const enum` into actual output code. It transpiles it into a basic JS object. This causes babel to not remove the transpiled `const enum`, as it is not just type information now. It can be import/exported, since it is just plain JS. Babel leaves the import/export to the module bundling system, such as webpack. Since it's a simple JS object, it can be inlined if you are using a minifier like terser.
